apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xsot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xsot
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xsot
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xsot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xsot
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-clas-tenant/rhtap-demo-app/hacbs-test-project-xsot@sha256:cab6c0ac9a9c675eb55f808405de1069ec2272c6e92884cb68dae0274a80d25d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
